### ISSUE TITLE
pages-content?

### ISSUE THREAD

**Issue by h2n0** [ConProgramming/Novus#1]
I've cloned the repo and run `npm install` but when I run `npm start` I get the following error.
 > Error: ENOENT: no such file or directory, scandir '/home/h2n0/Documents/MeshNet/meshnetworkdesktopPrototype/pages-content'
    at Object.fs.readdirSync (fs.js:910:18)
    at Object.<anonymous> (/home/h2n0/Documents/MeshNet/meshnetworkdesktopPrototype/helpers/page-build-helper.js:44:20)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.1.0 start: `node ./helpers/page-build-helper.js && electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/h2n0/.npm/_logs/2017-11-29T16_18_11_229Z-debug.log

This to me suggests that I am missing a directory called "pages-content" but looking back through the commits that directory has never existed.

Any ides on how to progress?

**Comment by ConProgramming** [comment]
I am on my phone right now, so I can't test, but if you add the folder pages-content to the main "meshnetworkdesktopPrototype" folder does that fix it?

**Comment by h2n0** [comment]
Caused due to a weird module, will be fixed later on
